"""add tax exempt fields to invoices

Revision ID: 3546d3b94b99
Revises: 33a3c4534a9a
Create Date: 2026-02-14 16:16:57.520498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3546d3b94b99'
down_revision: Union[str, Sequence[str], None] = '33a3c4534a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_tax_exempt', sa.Boolean(), nullable=False))
    op.add_column('invoices', sa.Column('tax_exempt_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'tax_exempt_reason')
    op.drop_column('invoices', 'is_tax_exempt')
    # ### end Alembic commands ###
